# Generated by Django 4.2.4 on 2023-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
