# Generated by Django 4.2.4 on 2023-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_img',
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='category_image'),
        ),
    ]
