# Generated by Django 4.2.4 on 2023-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_category_img_category_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
